[package]
name = "harbor"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "Harbor"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.8"
pollster = "0.4.0"
wgpu = "27.0.1"
winit = "0.30.12"
tracy-client = { version = "0.17", features = ["enable"] }

[features]
transparent = []
